[package]
name = "ogawa-rs"
version = "0.1.0"
authors = ["Traverse Research <info@traverseresearch.nl>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Ogawa Alembic Cache file parser."
homepage = "https://github.com/Traverse-Research/ogawa-rs"
repository = "https://github.com/Traverse-Research/ogawa-rs"
keywords = ["ogawa", "alembic", ".abc"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

include = [
    "src/**",
    "Cargo.toml"
]

[dependencies]
thiserror = "1.0"
anyhow = "1.0"
byteorder = "1.3.4"
half = "1.6.0"
vmap = "0.4.2"

[workspace]
members = [
    "apps/schema-parsing",
    "apps/print-tree",
    "apps/curves-test-vis",
]
