
pre-release-commit-message = "Release {{version}}"
dev-version = false
tag-message = "Release {{version}}"
tag-name = "{{version}}"
sign-commit = true
sign-tag = true
publish = false

pre-release-replacements = [
  {file="README.md", search="ogawa-rs = .*", replace="{{crate_name}} = \"{{version}}\""},
]
