on: [push, pull_request]

name: Continuous integration

jobs:
  check:
    name: Check
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install xkbcommon-sys
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install libxkbcommon-dev
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
            ${{ runner.os }}-
      - run: cargo check --workspace --all-targets

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Install xkbcommon-sys
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install libxkbcommon-dev
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
            ${{ runner.os }}-
      - run: cargo fmt --all -- --check
      - run: cargo clippy --workspace --all-targets -- -D warnings

  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Install xkbcommon-sys
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install libxkbcommon-dev
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-test-
            ${{ runner.os }}-cargo-
            ${{ runner.os }}-
      - run: cargo test --workspace --all-targets
